---
- name: Install required packages
  loop:
    - cifs-utils
  ansible.builtin.package:
    name: '{{ item }}'
    state: present
  tags:
    - storage

- name: Create required path
  ansible.builtin.file:
    path: '{{ storage_path }}'
    state: directory
    owner: root
    group: root
    mode: u=rwx,g=rx,o=rx
  tags:
    - storage

- name: Write credentials file
  ansible.builtin.template:
    src: credentials.j2
    dest: /etc/smbpasswd
    owner: root
    group: root
    mode: u=rw,g=rw,o=
  tags:
    - storage

- name: Mount storage volume
  ansible.posix.mount:
    path: '{{ storage_path }}'
    src: '//{{ storage_server }}/{{ storage_share }}'
    fstype: cifs
    opts: '{{ storage_options | join(",") }}'
    state: mounted
  tags:
    - storage

...
