# Standards: 1.2
---
- name: Install required packages
  loop:
    - cifs-utils
  package:
    name: '{{ item }}'
    state: present
  tags:
    - storage

- name: Create required path
  file:
    path: '{{ storage_path }}'
    state: directory
  tags:
    - storage

- name: Write credentials file
  template:
    src: credentials.j2
    dest: /etc/smbpasswd
    owner: root
    group: root
    mode: u=rw,g=rw,o=
  tags:
    - storage

- name: Mount storage volume
  mount:
    path: '{{ storage_path }}'
    src: '//{{ storage_server }}/{{ storage_share }}'
    fstype: cifs
    opts: '{{ storage_options | join(",") }}'
    state: mounted
  tags:
    - storage

...
